name: Build and deploy Python app to Azure Web App - pa200-hw2-flaskapp

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python version
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m venv antenv
          source antenv/bin/activate
          pip install -r requirements.txt

      - name: Upload artifact for deployment
        uses: actions/upload-artifact@v4
        with:
          name: python-app
          path: |
            .
            !antenv/

      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: python-app

      - name: Upload static files to Blob Storage
        run: |
          az storage blob upload-batch \
            --account-name pa200hw2staticra  \
            --destination static \
            --source ./static \
            --overwrite true \
            --account-key ${{ secrets.STORAGE_ACCOUNT_KEY }}

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'pa200-hw2-flaskapp'
          slot-name: 'Production'
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE }}
          package: .